title: Graph Gallery
email: mogproj [at] gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Graph is art; graph is universe.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-seo-tag

compress_html:
  blanklines: true

mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

  # defaults:
  # - scope:
  #     path: "assets/img"
  #   values:
  #     image: true

color_scheme: gg
footer_content: "&copy; 2021-2022 <a href=\"https://mogproject.com\" target=\"_blank\">mogproject</a>. All rights reserved."


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
